name: asia_trinity
description: Asia Trinity Investment
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  bloc: ^8.1.4
  dio: ^5.7.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  fpdart: ^1.1.0
  freezed_annotation: ^2.4.4
  get_it: ^8.0.0
  go_router: ^14.6.2
  google_fonts: ^6.2.1
  intl: ^0.19.0
  json_annotation: ^4.9.0
  talker: ^4.5.2
  talker_logger: ^4.5.2
  talker_bloc_logger: ^4.5.2
  talker_dio_logger: ^4.5.2
  talker_flutter: ^4.5.2

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.13
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/pngs/